FROM php:8.5-fpm

ENV OPCACHE_VALIDATE_TIMESTAMPS=0

RUN apt update \
    && apt install -y zlib1g-dev g++ git libicu-dev zip libzip-dev zip libcurl4-openssl-dev pkg-config libssl-dev cron nginx libpng-dev libjpeg62-turbo-dev libwebp-dev;
RUN docker-php-ext-configure gd --with-jpeg --with-webp \
    && docker-php-ext-install intl pdo pdo_mysql gd;
RUN pecl install apcu \
    && docker-php-ext-enable apcu;
RUN docker-php-ext-configure zip \
    && docker-php-ext-install zip \
    && pecl clear-cache;

# Use the default production configuration
RUN ln -s ${PHP_INI_DIR}/php.ini-production ${PHP_INI_DIR}/php.ini \
    && sed -i -e "s/^ *memory_limit.*/memory_limit = 512M/g"  ${PHP_INI_DIR}/php.ini

COPY docker/php/conf.d/php-fpm.conf /usr/local/etc/php-fpm.d/www.conf

# Copy default settings
COPY docker/php/conf.d/cookbook.ini ${PHP_INI_DIR}/conf.d/cookbook.ini

WORKDIR /var/www/html

COPY docker/nginx/conf.d/default.dev.conf /etc/nginx/conf.d/default.conf

CMD ["php-fpm"]

ENV COMPOSER_ALLOW_SUPERUSER=1

COPY --from=composer:2.9.2 /usr/bin/composer /usr/bin/composer

RUN set -xe; \
    mkdir ~/.composer;

COPY app /var/www/html
RUN composer install --prefer-dist --no-progress -o --no-interaction --ignore-platform-reqs

COPY docker/docker-entrypoint.sh /usr/local/bin/docker-entrypoint
RUN chmod +x /usr/local/bin/docker-entrypoint

VOLUME /var/www/html

ENTRYPOINT ["docker-entrypoint"]
