FROM php:8.5-fpm as build

ENV OPCACHE_VALIDATE_TIMESTAMPS=0

RUN apt update \
    && apt install -y zlib1g-dev g++ git libicu-dev zip libzip-dev zip libcurl4-openssl-dev pkg-config libssl-dev cron nginx libpng-dev libjpeg62-turbo-dev libwebp-dev;
RUN docker-php-ext-configure gd --with-jpeg --with-webp \
    && docker-php-ext-install intl pdo pdo_mysql gd;
RUN pecl install apcu \
    && docker-php-ext-enable apcu;
RUN docker-php-ext-configure zip \
    && docker-php-ext-install zip \
    && pecl clear-cache;

# Use the default production configuration
RUN ln -s ${PHP_INI_DIR}/php.ini-production ${PHP_INI_DIR}/php.ini \
    && sed -i -e "s/^ *memory_limit.*/memory_limit = 512M/g"  ${PHP_INI_DIR}/php.ini

COPY docker/php/conf.d/php-fpm.conf /usr/local/etc/php-fpm.d/www.conf

# Copy default settings
COPY docker/php/conf.d/cookbook.ini ${PHP_INI_DIR}/conf.d/cookbook.ini

COPY docker/nginx/conf.d/default.prod.conf /etc/nginx/conf.d/default.conf
RUN rm /etc/nginx/sites-enabled/default

CMD ["php-fpm"]

ENV COMPOSER_ALLOW_SUPERUSER=1
ENV APP_ENV=prod

COPY --from=composer:2.9.2 /usr/bin/composer /usr/bin/composer

RUN set -xe; \
    mkdir ~/.composer;

COPY app /var/www/html
RUN composer install --prefer-dist --no-progress -o --no-interaction --ignore-platform-reqs

COPY docker/docker-entrypoint.sh /usr/local/bin/docker-entrypoint
RUN chmod +x /usr/local/bin/docker-entrypoint

ENTRYPOINT ["docker-entrypoint"]

FROM node:18 as npm_builder

WORKDIR /app
COPY ../../app/package*.json ./
COPY --from=build /var/www/html/vendor ./vendor

RUN npm install --production=false

COPY ../../app .

RUN npm run build

FROM build as final

WORKDIR /var/www/html
COPY --from=npm_builder /app/public/build ./public/build
