services:
  app:
    image: cookbook-app:local
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile.dev
    environment:
      OPCACHE_VALIDATE_TIMESTAMPS: 1
      ENV: test
    volumes:
      - ./app:/var/www/html:rw,cached
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '${APP_PORT}:80'
    volumes:
      - ./app/public:/var/www/html/public
      - ./docker/nginx/conf.d/default.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  database:
      image: mysql:latest
      environment:
        MYSQL_DATABASE: cookbook
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: dbuser
        MYSQL_PASSWORD: dbpassword
      volumes:
        - db_data:/var/lib/mysql:rw
  worker:
    image: cookbook-app:local
    command: php bin/console messenger:consume async failed --time-limit=3600 --failure-limit=5
    restart: unless-stopped
    environment:
      OPCACHE_VALIDATE_TIMESTAMPS: 1
      ENV: prod
    volumes:
      - ./app:/var/www/html:rw,cached
    depends_on:
      - app
      - database
  database_test:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: cookbook_test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    volumes:
      - db_data_test:/var/lib/mysql:rw
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
volumes:
  db_data: {}
  db_data_test: {}
