# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        active.storage:
            local:
                directory: '%kernel.project_dir%/public/uploads/images'
